apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  namespace: dev
  labels:
    app: resume-backend
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
        environment: dev
    spec:
      containers:
      - name: backend
        image: resume-backend:latest
        ports:
        - containerPort: 9001
        env:
        - name: NODE_ENV
          value: "development"
        - name: PORT
          value: "9001"
        - name: HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/hello
            port: 9001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 9001
          initialDelaySeconds: 5
          periodSeconds: 5 