version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_MODE: ${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - resume-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - HOST=0.0.0.0
    # env_file is handled globally via --env-file flag
    networks:
      - resume-network

networks:
  resume-network:
    driver: bridge 