version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        VITE_MODE: ${NODE_ENV}
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - resume-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
      - HOST=0.0.0.0
    # env_file is handled globally via --env-file flag
    networks:
      - resume-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

networks:
  resume-network:
    driver: bridge 