apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resume-backend.fullname" . }}
  labels:
    app: {{ include "resume-backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "resume-backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "resume-backend.name" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }} 