apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume-frontend.fullname" . }}
  labels:
    app: {{ include "resume-frontend.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "resume-frontend.name" . }} 