apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-backend
  namespace: prod
  labels:
    app: resume-backend
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: resume-backend
  template:
    metadata:
      labels:
        app: resume-backend
        environment: prod
    spec:
      containers:
      - name: backend
        image: resume-backend:latest
        ports:
        - containerPort: 9005
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "9005"
        - name: HOST
          value: "0.0.0.0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/hello
            port: 9005
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 9005
          initialDelaySeconds: 5
          periodSeconds: 5 