apiVersion: v1
kind: Service
metadata:
  name: resume-frontend-service
  namespace: prod
  labels:
    app: resume-frontend
    environment: prod
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30084
  selector:
    app: resume-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: resume-backend-service
  namespace: prod
  labels:
    app: resume-backend
    environment: prod
spec:
  type: NodePort
  ports:
  - port: 9005
    targetPort: 9005
    protocol: TCP
    name: http
    nodePort: 30085
  selector:
    app: resume-backend 